const TOGGLE_MENU = 'TOGGLE_MENU'
const SWITCH_FALSE_NAV = 'SWITCH_FALSE_NAV'
const TOGGLE_UNDER_MENU = 'TOGGLE_UNDER_MENU'
const SWITCH_FALSE_UNDER_NAV = 'SWITCH_FALSE_UNDER_NAV'

export {
  TOGGLE_MENU,
  SWITCH_FALSE_NAV,
  TOGGLE_UNDER_MENU,
  SWITCH_FALSE_UNDER_NAV
}
