const TOGLE_MENU = 'TOGLE_MENU'
const SWITCH_FALSE_NAV = 'SWITCH_FALSE_NAV'
const TOGLE_UNDER_MENU = 'TOGLE_UNDER_MENU'
const SWITCH_FALSE_UNDER_NAV = 'SWITCH_FALSE_UNDER_NAV'

export {
  TOGLE_MENU,
  SWITCH_FALSE_NAV,
  TOGLE_UNDER_MENU,
  SWITCH_FALSE_UNDER_NAV
}
